### ISSUE TITLE
Fastify 5 support

### ISSUE THREAD

**Issue by ivstiv** [immobiliare/fastify-sentry#726]
Fastify 5 has been released, I've tried this library with it, but I get the following error:

```
FastifyError [Error]: fastify-plugin: @immobiliarelabs/fastify-sentry - expected '4.x' fastify version, '5.0.0' is installed
    at Object.checkVersion (/app/node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/pluginUtils.js:125:11)
    at Object.registerPlugin (/app/node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/pluginUtils.js:148:16)
    at Boot.override (/app/node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/pluginOverride.js:28:57)
    at Boot._loadPlugin (/app/node_modules/.pnpm/avvio@9.0.0/node_modules/avvio/boot.js:425:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
  statusCode: 500
}
```

Can you add support for Fastify v5?

**Comment by dnlup** [comment]
Hey @ivstiv , yes support for fastify 5 is on our roadmap. We'll try to add it as soon as possible

**Comment by C0kkie** [comment]
Hey

is there any eta?

**Comment by rgrzesk** [comment]
Hi!

Any update on that?

**Comment by dnlup** [comment]
Yes, I was looking into it and wanted to couple the fastify upgrade and the Sentry SDK upgrade into a single breaking change so it will take a little more work than expected, I'll get back to you when everything is ready, right now I am a little busy on another project.
